var Hotcake;
"undefined"===typeof Hotcake&&function(){var b;b={};Hotcake=function(){var a,e,c;Hotcake={};a=[];c={};Hotcake.define=function(a,e,c){return"function"===typeof e?b.defineLinkedClass(a,e,c):b.defineSingleClass(a,e,c)};Hotcake.hotswap=function(d){var c,h;if(e)console.error("Hotcake can only perform one hotswap at a time.");else{e=!0;c=document.getElementsByTagName("script");d||(d={});"undefined"===typeof d.loadStyles&&(d.loadStyles=!0);d.filterArray||(d.filterArray=[]);a.splice(0);for(var f=0;f<c.length;f++)h=
c[f],(h=h.attributes.src)&&h.value&&(d.loadForeign||d.loadForeign||b.isRelativeScript(h.value))&&!b.isIgnoredScript(d.filterArray,h.value)&&a.push({name:h.value});if(d.include&&d.include.length&&0<d.include.length)for(f=0;f<d.include.length;f++)a.push({name:d.include[f]});for(f=0;f<a.length;f++)b.hotloadScript(a[f],d.async);d.loadStyles&&Hotcake.hotswapStyles({include:d.includeStyles});d.loadFragments&&Hotcake.hotloadHandlebarsTemplates({include:d.includeFragments})}};Hotcake.hotswapStyles=function(a){for(var c=
0;c<document.styleSheets.length;c++)a=document.styleSheets[c],b.hotswapStyle(a.href,a.ownerNode)};Hotcake.getHandlebarsTemplate=function(a,b){var e,f;if(c[a])return c[a];request=new XMLHttpRequest;request.onload=function(b){if(f=b.target.responseText)e=Handlebars.compile(f),c[a]=e};request.open("GET",a,b);try{request.send()}catch(k){console.error(k)}return e};Hotcake.hotloadHandlebarsTemplates=function(a){var b,e;b=Object.keys(c);for(var f=0;f<b.length;f++)e=b[f],c[e]=null,getHandlebarsTemplate(e,
a&&a.async)};return Hotcake}();"undefined"!==typeof window._hotcakeDebug&&!0===window._hotcakeDebug&&(Hotcake._private=b);b.copyKeys=function(a,e){var c,d;e.prototype&&b.copyKeys(a,e.prototype);c=Object.getOwnPropertyNames(e);for(var g=0;g<c.length;g++)d=c[g],a[d]=e[d]};b.defineSingleClass=function(a,e,c){if(a)return c&&(b.copyKeys(a.prototype,c),a.prototype._baseClass=c),e&&b.copyKeys(a.prototype,e),a;a=function(){this.ctor&&"function"===typeof this.ctor?this.ctor.apply(this,arguments):c&&c.ctor&&
"function"===typeof c.ctor&&c.ctor.apply(this,arguments)};c&&(b.copyKeys(a.prototype,c.prototype),a.prototype._baseClass=c);e&&b.copyKeys(a.prototype,e);return a};b.defineLinkedClass=function(a,e,c){var d;d=function(){"function"===typeof e&&(this.constructor=e.constructor,e.apply(this,arguments));this.ctor&&"function"===typeof this.ctor?this.ctor.apply(this,arguments):c&&c.ctor&&"function"===typeof c.ctor&&c.ctor.apply(this,arguments)};c&&(b.copyKeys(d.prototype,c.prototype),d.prototype._baseClass=
c);e&&("function"===typeof e&&(e.__super__&&b.copyBackboneSuperKeys(d.prototype,e.__super__),b.copyKeys(d.prototype,e)),b.copyKeys(d,e));b.delegateKeys(d.prototype);a&&b.delegateKeysReplace(a.prototype,d.prototype);return d};b.delegateKeys=function(a){var e,c,d;e=Object.getOwnPropertyNames(a);for(var g=0;g<e.length;g++)c=e[g],d=a[c],"function"===typeof a[c]&&(a[c]=b.delegateForwardFunction(c,d))};b.delegateForwardFunction=function(a,b){return function(){if(this[a]._hotcakeReplacement){for(;this[a]._hotcakeReplacement;)this[a]=
this[a]._hotcakeReplacement;return this[a].apply(this,arguments)}return b.apply(this,arguments)}};b.copyBackboneSuperKeys=function(a,e){e.__super__&&b.copyBackboneSuperKeys(a,e.__super__);b.copyKeys(a,e)};b.delegateKeysReplace=function(a,b){var c,d;c=Object.keys(b);for(var g=0;g<c.length;g++)d=c[g],a[d]&&(a[d]._hotcakeReplacement=b[d])};b.isRelativeScript=function(a){return"/"==a.charAt(0)&&"/"==a.charAt(1)||0<=a.indexOf("://")?!1:!0};b.escapeRegex=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,
"\\$1").replace(/\x08/g,"\\x08")};b.isIgnoredScript=function(a,e){for(var c,d=0;d<a.length;d++)if(c=new RegExp("^"+b.escapeRegex(a[d]),"i"),c.test(e))return!0;return!1};b.hotloadScript=function(a,e){var c,d;d=b.appendGUID(a.name);c=new XMLHttpRequest;c.onload=function(c){b.pushScriptHotload(c,a)};c.open("GET",d,e);try{c.send()}catch(g){console.error("Error while loading or evaluating script file '"+d+"':"),console.error(g)}};b.pushScriptHotload=function(a,e){respondedScripts++;a.target.responseText&&
(e.body=a.target.responseText);respondedScripts==totalScripts&&b.evaluateHotload()};b.evaluateHotload=function(){for(var a=0;a<loadScripts.length;a++)try{b.suspendJQueryReady(),eval.call(window,loadScripts[a].body)}catch(e){console.error(e)}b.resumeJQueryReady();hotswapping=!1;onswapped&&"function"===typeof onswapped&&onswapped()};b.noop=function(){};b.suspendJQueryReady=function(){"undefined"!==typeof $&&$.prototype.ready!==b.noop&&(readyFunction=$.prototype.ready,$.prototype.ready=$.ready=b.noop)};
b.resumeJQueryReady=function(){"undefined"!==typeof $&&($.prototype.ready=$.ready=readyFunction)};b.hotswapStyle=function(a,e){var c,d;c=document.getElementsByTagName("head")[0];a=b.appendGUID(a);d=document.createElement("link");d.setAttribute("rel","stylesheet");d.setAttribute("href",a);c.appendChild(d);if(e){request=new XMLHttpRequest;request.onload=function(){e.remove()};request.open("GET",b.appendGUID(a),!0);try{request.send()}catch(g){}}};b.guid_p8=function(a){var b=(Math.random().toString(16)+
"000000000").substr(2,8);return a?"-"+b.substr(0,4)+"-"+b.substr(4,4):b};b.generateGUID=function(){return b.guid_p8()+b.guid_p8(!0)+b.guid_p8(!0)+b.guid_p8()};b.appendGUID=function(a){a=0<a.indexOf("?")?a+"&":a+"?";return a+"__hotcakeGUID="+b.generateGUID()}}();
