var Hotcake;
"undefined"===typeof Hotcake&&(Hotcake=function(){var f,n,p,q,r,s,t,u,v,w,h,l,x,k,m,g;Hotcake={};h=[];g={};f=function(a,c){var b,d;c.prototype&&f(a,c.prototype);b=Object.getOwnPropertyNames(c);for(var e=0;e<b.length;e++)d=b[e],a[d]=c[d]};Hotcake.define=function(a,c,b){return"function"===typeof c?defineLinkedClass(a,c,b):defineSingleClass(a,c,b)};defineSingleClass=function(a,c,b){if(a)return b&&(f(a.prototype,b),a.prototype._baseClass=b),c&&f(a.prototype,c),a;a=function(){this.ctor&&"function"===typeof this.ctor?
this.ctor.apply(this,arguments):b&&b.ctor&&"function"===typeof b.ctor&&b.ctor.apply(this,arguments)};b&&(f(a.prototype,b.prototype),a.prototype._baseClass=b);c&&f(a.prototype,c);return a};defineLinkedClass=function(a,c,b){var d;d=function(){"function"===typeof c&&(this.constructor=c.constructor,c.apply(this,arguments));this.ctor&&"function"===typeof this.ctor?this.ctor.apply(this,arguments):b&&b.ctor&&"function"===typeof b.ctor&&b.ctor.apply(this,arguments)};b&&(f(d.prototype,b.prototype),d.prototype._baseClass=
b);c&&("function"===typeof c&&(c.__super__&&copyBackboneSuperKeys(d.prototype,c.__super__),f(d.prototype,c)),f(d,c));n(d.prototype);a&&delegateKeysReplace(a.prototype,d.prototype);return d};n=function(a){var c,b,d;c=Object.getOwnPropertyNames(a);for(var e=0;e<c.length;e++)b=c[e],d=a[b],"function"===typeof a[b]&&(a[b]=delegateForwardFunction(b,d))};delegateForwardFunction=function(a,c){return function(){if(this[a]._hotcakeReplacement){for(;this[a]._hotcakeReplacement;)this[a]=this[a]._hotcakeReplacement;
return this[a].apply(this,arguments)}return c.apply(this,arguments)}};copyBackboneSuperKeys=function(a,c){c.__super__&&copyBackboneSuperKeys(a,c.__super__);f(a,c)};delegateKeysReplace=function(a,c){var b,d;b=Object.keys(c);for(var e=0;e<b.length;e++)d=b[e],a[d]&&(a[d]._hotcakeReplacement=c[d])};Hotcake.hotswap=function(a){var c,b,d;if(m)console.error("Hotcake can only perform one hotswap at a time.");else{m=!0;c=document.getElementsByTagName("script");a||(a={});k=a.onswapped;"undefined"===typeof a.loadStyles&&
(a.loadStyles=!0);a.filterArray||(a.filterArray=[]);d=[];for(var e=0;e<c.length;e++)b=c[e],(b=b.attributes.src)&&b.value&&(a.loadForeign||a.loadForeign||p(b.value))&&!isIgnoredScript(a.filterArray,b.value)&&d.push(b.value);if(a.include&&a.include.length&&0<a.include.length)for(e=0;e<a.include.length;e++)d.push(a.include[e]);x=d.length;h.splice(0);for(e=l=0;e<d.length;e++)u(d[e],a.async);a.loadStyles&&Hotcake.hotswapStyles({include:a.includeStyles})}};p=function(a){return"/"==a.charAt(0)&&"/"==a.charAt(1)||
0<=a.indexOf("://")?!1:!0};escapeRegex=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};isIgnoredScript=function(a,c){for(var b,d=0;d<a.length;d++)if(b=new RegExp("^"+escapeRegex(a[d]),"i"),b.test(c))return!0;return!1};u=function(a,c){var b;b=new XMLHttpRequest;b.onload=q;b.open("GET",a,c);try{b.send()}catch(d){console.error("Error while loading or evaluating script file '"+a+"':"),console.error(d)}};q=function(a){l++;a.target.responseText&&h.push(a.target.responseText);
l==x&&r()};r=function(){for(var a=0;a<h.length;a++)try{t(),eval.call(window,h[a])}catch(c){console.error(c)}s();m=!1;k&&"function"===typeof k&&k()};noop=function(){};t=function(){$.prototype.ready!==noop&&(w=$.prototype.ready,$.prototype.ready=$.ready=noop)};s=function(){$.prototype.ready=$.ready=w};Hotcake.hotswapStyles=function(a){for(var c=0;c<document.styleSheets.length;c++)a=document.styleSheets[c],v(a.href,a.ownerNode)};v=function(a,c){var b,d;b=document.getElementsByTagName("head")[0];d=document.createElement("link");
d.setAttribute("rel","stylesheet");d.setAttribute("href",a);b.appendChild(d);if(c){request=new XMLHttpRequest;request.onload=function(){c.remove()};request.open("GET",a,!0);try{request.send()}catch(e){}}};Hotcake.getHandlebarsTemplate=function(a,c){var b,d;if(g[a])return g[a];request=new XMLHttpRequest;request.onload=function(c){if(d=c.target.responseText)b=Handlebars.compile(d),g[a]=b};request.open("GET",a,c);try{request.send()}catch(e){console.error(e)}return b};Hotcake.hotloadHandlebarsTemplates=
function(a){var c,b;c=Object.keys(g);for(var d=0;d<c.length;d++)b=c[d],g[b]=null,getHandlebarsTemplate(b,a&&a.async)};return Hotcake}());
