var Hotcake;
"undefined"===typeof Hotcake&&function(){var c,m,g,k,n,h,l;c={};Hotcake=function(){Hotcake={};g=[];var b={};Hotcake.define=function(a,b,d){return"function"===typeof b?c.defineLinkedClass(a,b,d):c.defineSingleClass(a,b,d)};Hotcake.hotswap=function(a){var b,d;if(l)console.error("Hotcake can only perform one hotswap at a time.");else{l=!0;b=document.getElementsByTagName("script");a||(a={});h=a.onswapped;"undefined"===typeof a.loadStyles&&(a.loadStyles=!0);a.filterArray||(a.filterArray=[]);g.splice(0);
for(var f=0;f<b.length;f++)d=b[f],(d=d.attributes.src)&&d.value&&(a.loadForeign||a.loadForeign||c.isRelativeScript(d.value))&&!c.isIgnoredScript(a.filterArray,d.value)&&g.push({name:d.value});if(a.include&&a.include.length&&0<a.include.length)for(f=0;f<a.include.length;f++)g.push({name:a.include[f]});n=g.length;for(f=k=0;f<g.length;f++)c.hotloadScript(g[f],a.async);a.loadStyles&&Hotcake.hotswapStyles({include:a.includeStyles});a.loadFragments&&Hotcake.hotloadHandlebarsTemplates({include:a.includeFragments})}};
Hotcake.hotswapStyles=function(a){for(var b=0;b<document.styleSheets.length;b++)a=document.styleSheets[b],c.hotswapStyle(a.href,a.ownerNode)};Hotcake.getHandlebarsTemplate=function(a,c){var d,f;if(b[a])return b[a];request=new XMLHttpRequest;request.onload=function(c){if(f=c.target.responseText)d=Handlebars.compile(f),b[a]=d};request.open("GET",a,c);try{request.send()}catch(g){console.error(g)}return d};Hotcake.hotloadHandlebarsTemplates=function(a){var c,d;c=Object.keys(b);for(var f=0;f<c.length;f++)d=
c[f],b[d]=null,getHandlebarsTemplate(d,a&&a.async)};return Hotcake}();"undefined"!==typeof window._hotcakeDebug&&!0===window._hotcakeDebug&&(Hotcake._private=c);c.copyKeys=function(b,a){var e,d;a.prototype&&c.copyKeys(b,a.prototype);e=Object.getOwnPropertyNames(a);for(var f=0;f<e.length;f++)d=e[f],b[d]=a[d]};c.defineSingleClass=function(b,a,e){if(b)return e&&(c.copyKeys(b.prototype,e),b.prototype._baseClass=e),a&&c.copyKeys(b.prototype,a),b;b=function(){this.ctor&&"function"===typeof this.ctor?this.ctor.apply(this,
arguments):e&&e.ctor&&"function"===typeof e.ctor&&e.ctor.apply(this,arguments)};e&&(c.copyKeys(b.prototype,e.prototype),b.prototype._baseClass=e);a&&c.copyKeys(b.prototype,a);return b};c.defineLinkedClass=function(b,a,e){var d;d=function(){"function"===typeof a&&(this.constructor=a.constructor,a.apply(this,arguments));this.ctor&&"function"===typeof this.ctor?this.ctor.apply(this,arguments):e&&e.ctor&&"function"===typeof e.ctor&&e.ctor.apply(this,arguments)};e&&(c.copyKeys(d.prototype,e.prototype),
d.prototype._baseClass=e);a&&("function"===typeof a&&(a.__super__&&c.copyBackboneSuperKeys(d.prototype,a.__super__),c.copyKeys(d.prototype,a)),c.copyKeys(d,a));c.delegateKeys(d.prototype);b&&c.delegateKeysReplace(b.prototype,d.prototype);return d};c.delegateKeys=function(b){var a,e,d;a=Object.getOwnPropertyNames(b);for(var f=0;f<a.length;f++)e=a[f],d=b[e],"function"===typeof b[e]&&(b[e]=c.delegateForwardFunction(e,d))};c.delegateForwardFunction=function(b,a){return function(){if(this[b]._hotcakeReplacement){for(;this[b]._hotcakeReplacement;)this[b]=
this[b]._hotcakeReplacement;return this[b].apply(this,arguments)}return a.apply(this,arguments)}};c.copyBackboneSuperKeys=function(b,a){a.__super__&&c.copyBackboneSuperKeys(b,a.__super__);c.copyKeys(b,a)};c.delegateKeysReplace=function(b,a){var c,d;c=Object.keys(a);for(var f=0;f<c.length;f++)d=c[f],b[d]&&(b[d]._hotcakeReplacement=a[d])};c.isRelativeScript=function(b){return"/"==b.charAt(0)&&"/"==b.charAt(1)||0<=b.indexOf("://")?!1:!0};c.escapeRegex=function(b){return String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,
"\\$1").replace(/\x08/g,"\\x08")};c.isIgnoredScript=function(b,a){for(var e,d=0;d<b.length;d++)if(e=new RegExp("^"+c.escapeRegex(b[d]),"i"),e.test(a))return!0;return!1};c.hotloadScript=function(b,a){var e,d;d=c.appendGUID(b.name);e=new XMLHttpRequest;e.onload=function(a){c.pushScriptHotload(a,b)};e.open("GET",d,a);try{e.send()}catch(f){console.error("Error while loading or evaluating script file '"+d+"':"),console.error(f)}};c.pushScriptHotload=function(b,a){k++;b.target.responseText&&(a.body=b.target.responseText);
k==n&&c.evaluateHotload()};c.evaluateHotload=function(){for(var b=0;b<g.length;b++)try{c.suspendJQueryReady(),eval.call(window,g[b].body)}catch(a){console.error(a)}c.resumeJQueryReady();l=!1;h&&"function"===typeof h&&h()};c.noop=function(){};c.suspendJQueryReady=function(){"undefined"!==typeof $&&$.prototype.ready!==c.noop&&(m=$.prototype.ready,$.prototype.ready=$.ready=c.noop)};c.resumeJQueryReady=function(){"undefined"!==typeof $&&($.prototype.ready=$.ready=m)};c.hotswapStyle=function(b,a){var e,
d;e=document.getElementsByTagName("head")[0];b=c.appendGUID(b);d=document.createElement("link");d.setAttribute("rel","stylesheet");d.setAttribute("href",b);e.appendChild(d);if(a){request=new XMLHttpRequest;request.onload=function(){a.remove()};request.open("GET",c.appendGUID(b),!0);try{request.send()}catch(f){}}};c.guid_p8=function(b){var a=(Math.random().toString(16)+"000000000").substr(2,8);return b?"-"+a.substr(0,4)+"-"+a.substr(4,4):a};c.generateGUID=function(){return c.guid_p8()+c.guid_p8(!0)+
c.guid_p8(!0)+c.guid_p8()};c.appendGUID=function(b){b=0<b.indexOf("?")?b+"&":b+"?";return b+"__hotcakeGUID="+c.generateGUID()}}();
